// <auto-generated />
namespace web_shop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addednewvariable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addednewvariable));
        
        string IMigrationMetadata.Id
        {
            get { return "201702091324116_added new variable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
